apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka"
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: debezium/kafka
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9093
          name: kafka-external
        command: ["/bin/sh"]
        args: ["-c", "BROKER_ID=${POD_NAME##*-} KAFKA_ADVERTISED_LISTENERS=EXTERNAL://localhost:3000${POD_NAME##*-},INTERNAL://$(POD_NAME).kafka.default.svc:9092 /docker-entrypoint.sh start"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ZOOKEEPER_CONNECT
          value: "zookeeper.default.svc:2181"
        # - name: KAFKA_ADVERTISED_LISTENERS
          # value: "PLAINTEXT://kafka-0.kafka-headless.default.svc.cluster.local:9092"
        - name: KAFKA_LISTENERS
          value: "EXTERNAL://:9093,INTERNAL://:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"


# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: kafka
# spec:
#   selector:
#     matchLabels:
#       app: kafka
#   serviceName: "kafka"
#   replicas: 3
#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       containers:
#       - name: kafka
#         image: debezium/kafka
#         ports:
#         - containerPort: 9092
#           name: kafka
#         - containerPort: 9093
#           name: kafka-external
#         command:
#         - "/bin/sh"
#         args:
#         - "-c"
#         - |
#           export BROKER_ID=${POD_NAME##*-}
#           export KAFKA_ADVERTISED_LISTENERS="EXTERNAL://localhost:3000${POD_NAME##*-},INTERNAL://$(POD_NAME).kafka.default.svc:9092"
#           export KAFKA_LISTENERS="EXTERNAL://:9093,INTERNAL://:9092"
#           export KAFKA_INTER_BROKER_LISTENER_NAME="INTERNAL"
#           export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
#           /docker-entrypoint.sh start
#         env:
#         - name: POD_NAME
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.name
#         - name: ZOOKEEPER_CONNECT
#           value: "zookeeper.default.svc:2181"


