apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-connector-configuration-role
  namespace: kafka
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["debezium-secret"]
  verbs: ["get"]