apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-connector-configuration-role-binding
  namespace: kafka
subjects:
- kind: ServiceAccount
  name: debezium-connect-cluster-connect
  namespace: kafka
roleRef:
  kind: Role
  name: kafka-connector-configuration-role
  apiGroup: rbac.authorization.k8s.io