apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "debezium-connector-mysql"
  namespace: kafka
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.hostname: 54.198.209.74 
    database.port: 30036
    database.user: root
    database.password: debezium
    database.server.id: "184054"
    database.whitelist: "inventory"
    database.server.name: "mysql"
    database.history.kafka.bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
    database.history.kafka.topic: "schema-changes.inventory"
    include.schema.changes: "true"
    database.allowPublicKeyRetrieval: "true"