apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: henry-connector-configuration-role-binding
  namespace: debezium
subjects:
- kind: ServiceAccount
  name: debezium-connect-cluster-connect
  namespace: debezium
roleRef:
  kind: Role
  name: henry-connector-configuration-role
  apiGroup: rbac.authorization.k8s.io