apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: henry-connectior-configuration-role
  namespace: debezium
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["debezium-secret"]
  verbs: ["get"]